### ISSUE TITLE
make gh-pages primary and delete master

### ISSUE THREAD

**Issue by ablwr** [MediaArea/MediaConch-Website#1]
Since this repository is a Jekyll-based site and Github automatically renders Jekyll sites when they are on the gh-pages branch, we should create that branch, make it the primary branch, and remove the master branch entirely so the ghpages site can act as a "staging" environment (despite image-linking discrepancies) to preview code changes prior to deployment on the MediaArea domain.

**Comment by ablwr** [comment]
I can do this. But not sure if I have "god status" of this repo...

**Comment by GuillaumeRoques** [comment]
I'm not confident with that for 2 reasons : mainly because you will have an error when cloning repository without a master and as we do not use GitHub pages it's simpler to use master directly (in order to use ghpages site for staging you can keep a gh-pages branch if you want)

**Comment by JeromeMartinez** [comment]
"staging" is with a local jekyll, from my point of view.

**Comment by ablwr** [comment]
Local jekyll is "development" from my point of view. ;)

But OK, I understand and am closing this issue!
