### ISSUE TITLE
MediaConchOnline not working

### ISSUE THREAD

**Issue by ts-avrd** [MediaArea/MediaConch-Website#116]
Hello, 

I've tried to access https://mediaarea.net/MediaConchOnline/ but it only shows a "500 - Internal Server Error". 

On a side note, I encountered the same when installing it on my own web server, but I'll create a separate ticket for that :) 

Kind regards, 
ts

**Comment by JeromeMartinez** [comment]
Just tested on my side, the URL works fine, but I tested only 1 of the 4 servers (geographical assignment), the European one.
In which country are you located (or what it is the IP address of the server on your side)?

**Comment by ts-avrd** [comment]
Hi!

Trying to connect to mediaarea.net which resolved to 217.182.128.108 for me. Geographical location is Austria. 

![image](https://user-images.githubusercontent.com/36546011/36325970-cbcef528-1359-11e8-92a8-9c4c59cac8d7.png)

Thank you for your fast response :) I asked @pjotrek-b to also try and he has the same problem.

**Comment by JeromeMartinez** [comment]
OK, the European server but in IPv4 (I have IPv6).
I have the error in IPv4, we'll look at this (big) issue.

**Comment by GuillaumeRoques** [comment]
It should work now, can you confirm ?

**Comment by ts-avrd** [comment]
Looks good, I've tested a file upload check and it worked fine :) Thank you for the fast fix! May I ask what was the issue?

**Comment by GuillaumeRoques** [comment]
I forgot to update the database schema, so it's working for existing users but not for the new ones :(
