### ISSUE TITLE
Test Demonstrations page links to policy which does not exist

### ISSUE THREAD

**Issue by sromkey** [MediaArea/MediaConch-Website#20]
Under "General conformance" the General Conformance XSL links to this: https://raw.githubusercontent.com/MediaArea/MediaConch_SourceCode/master/Source/Resource/policies/General_Conformance.xsl which can't be downloaded.

**Comment by dinahhandel** [comment]
This can't be downloaded because it doesn't exist. It was removed from the demonstration page for the time being.
